name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
      env:
        REACT_APP_API_ENDPOINT_URL : ${{ secrets.API_ENDPOINT }}
        REACT_APP_REGION : ${{ secrets.REGION }}
        REACT_APP_CLIENT_ID : ${{ secrets.CLIENT_ID }}
    
    - name: Build
      run: REACT_APP_VERSION=$(echo $(date +%y%m%d%M%H%S)-$(git rev-parse --short HEAD)-$(git rev-parse --abbrev-ref HEAD)) npm run build

    - name: Copy into bucket
      uses: ItsKarma/aws-cli@v1.70.0
      with:
        args: s3 sync build/ s3://$HOSTING_BUCKET/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.REGION }}
        HOSTING_BUCKET: ${{ secrets.HOSTING_BUCKET }}
