# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run test
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Test failed => close pull request
      if: ${{ failure() }}
      uses: superbrothers/close-pull-request@v3
      with:
        comment: "Sorry"

    - name: Test passed => merge pull request
      if: ${{ !failure() }}
      uses: "pascalgn/automerge-action@v0.14.3"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"